django_class/djangoProject2/djangoProject2/urls.py
from django.contrib import admin
from django.urls import path,re_path
from app02 import views
from django.conf import settings
from django.views.static import serve

# url和函数的对应关系
urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # path("admin/", admin.site.urls),
    # 登录路由
    path("login/",views.Login),
    #主界面
    path("main/",views.main),
    #部门管理
    path("depart/",views.depart),
    path("depart/add/",views.depart_add),
    path("depart/delete/",views.depart_delete),
    path("depart/<int:nid>/edit/",views.depart_edit), #传递动态的值

    #用户管理
    path("user/",views.user),
    path("user/add/",views.user_add),
    path("user/delete/",views.user_delete),
    path("user/<int:nid>/edit/",views.user_edit),

    #靓号管理
    path("phonenumber/",views.number),
    path("phonenumber/add/",views.number_add),
    path("phonenumber/delete/",views.number_delete),
    path("phonenumber/<int:nid>/edit/",views.number_edit),

    #文件上传
    path("file/",views.load_file),
    path("modelfile/",views.moelformfile),
    path("city/",views.citys)
]

django_class/djangoProject2/app02/models.py
from django.db import models


# Create your models here.
# 创建数据库表单
# 用户表
class UserInfo(models.Model):
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    enroll = models.DateField(verbose_name="入职时间")
    # 性别
    gender_choise = (
        (1, "男"),
        (2, "女")
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choise)
    # 无约束
    # depart_id = models.BigIntegerField(verbose_name="部门ID")

    # 1.有约束
    #   - to，与那张表关联
    #   - to_field，表中的那一列关联
    # 2.django自动
    #   - 写的depart
    #   - 生成数据列 depart_id
    # 3.部门表被删除
    # ### 3.1 级联删除/联表删除
    depart = models.ForeignKey(to="Department", to_field="id", on_delete=models.CASCADE, verbose_name="部门名称")
    # ### 3.2 置空
    # depart = models.ForeignKey(to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)


# 部门表
class Department(models.Model):
    title = models.CharField(verbose_name="标题", max_length=32)

    def __str__(self):
        return self.title


# 靓号管理
class PhoneNumber(models.Model):
    number = models.CharField(verbose_name="手机号", max_length=11)
    price = models.IntegerField(verbose_name="价格")
    level_choices = (
        (1, "一级"),
        (2, "二级"),
        (3, "三级"),
        (4, "四级")
    )
    status_choices = (
        (1, "已占用"),
        (2, "未占用")
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)


# 管理员
class Admin(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

class Admin1(models.Model):
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    img = models.CharField(verbose_name="图片",max_length=128)

class city(models.Model):
    name = models.CharField(verbose_name="名称", max_length=32)
    count = models.IntegerField(verbose_name="人口", max_length=64)
    img = models.FileField(verbose_name="LOGO", max_length=128,upload_to="city/")

django_class/djangoProject2/app02/views.py
import os

from django.forms import Form
from django.shortcuts import render, redirect, HttpResponse
from app02 import models
from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.conf import settings


# Create your views here.

# 写视图函数

# 登录视图函数
def Login(request):
    if request.method == "GET":
        return render(request, "login.html")
    else:
        # name = models.Admin.objects.
        if request.POST.get("username") == "admin" and request.POST.get("password") == "123456":
            return redirect('/main')
        else:
            return render(request, "login.html", {"message": "信息错误"})


# 主界面视图函数
def main(request):
    return HttpResponse("你好")


def depart(request):
    '''部门列表'''
    querset = models.Department.objects.all()
    return render(request, "depart.html", {"quersey": querset})


# 添加部门
def depart_add(request):
    if request.method == "GET":
        return render(request, "depart_add.html")
    title = request.POST.get("title")
    models.Department.objects.create(title=title)
    return redirect("/depart")


# 删除部门
def depart_delete(request):
    nid = request.GET.get('nid')
    models.Department.objects.filter(id=nid).delete()
    return redirect("/depart")


# 修改部门信息
def depart_edit(request, nid):
    if request.method == "GET":
        # value = request.GET.get('value')
        row_obj = models.Department.objects.filter(id=nid).first().title
        # print(row_obj)
        return render(request, "depart_edit.html", {'value': row_obj})
    else:
        new = request.POST.get('title')
        models.Department.objects.filter(id=nid).update(title=new)
        return redirect("/depart")


def user(request):
    '''用户管理'''
    users = models.UserInfo.objects.all()

    return render(request, "user.html", {"users": users})


class UserModelForm(forms.ModelForm):
    class Meta:
        model = models.UserInfo  # 不要加()
        fields = ["name", "password", "age", "enroll", "gender", "account", "depart"]
        widgets = {
            "password": forms.PasswordInput(attrs={"class": "form-control"})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}


def user_add(request):
    """添加用户ModelForm版本"""
    if request.method == "GET":
        form = UserModelForm()
        return render(request, 'user_add.html', {"form": form})

    form = UserModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect("/user")
    return render(request, 'user_add.html', {"form": form})


# 删除用户
def user_delete(request):
    nid = request.GET.get("nid")
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect("/user")


# 编辑用户
def user_edit(request, nid):
    row_obj = models.UserInfo.objects.filter(id=nid).first()
    if request.method == "GET":
        form = UserModelForm(instance=row_obj)
        return render(request, 'user_edit.html', {"form": form})
    else:
        form = UserModelForm(data=request.POST, instance=row_obj)
        if form.is_valid():
            form.save()
            return redirect("/user")
        return render(request, 'user_edit.html', {"form": form})


# 展示phonenumber
def number(request):
    data_dic = {}
    value = request.GET.get('q', '')
    if value:
        data_dic["number__contains"] = value
    numbers = models.PhoneNumber.objects.filter(**data_dic)
    return render(request, "number.html", {"number": numbers, "dates": value})


class numberform(forms.ModelForm):
    number = forms.CharField(label="手机号",
                             validators=[RegexValidator(r'^1\d{10}+$', '号码必须以1开头且11位')])

    class Meta:
        model = models.PhoneNumber
        fields = ['number', 'price', 'level', 'status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}

    def clean_number(self):
        # self.instance.pk
        txt_number = self.cleaned_data["number"]
        exists = models.PhoneNumber.objects.filter(number=txt_number).exists()
        if exists:
            raise ValidationError("手机号已存在")
        return txt_number


'''编辑'''


class edit(forms.ModelForm):
    number = forms.CharField(label="手机号",
                             validators=[RegexValidator(r'^1\d{10}+$', '号码必须以1开头且11位')])

    class Meta:
        model = models.PhoneNumber
        fields = ['number', 'price', 'level', 'status']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": field.label}

    def clean_number(self):
        self.instance.pk
        txt_number = self.cleaned_data["number"]
        exists = models.PhoneNumber.objects.exclude(id=self.instance.pk).filter(number=txt_number).exists()
        if exists:
            raise ValidationError("手机号已存在")
        return txt_number


# 添加靓号
def number_add(request):
    if request.method == "GET":
        form = numberform()
        return render(request, "number_add.html", {"form": form})
    else:
        form = numberform(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("/phonenumber/")
        return render(request, 'number_add.html', {"form": form})


# 删除靓号
def number_delete(request):
    nid = request.GET.get('nid')
    models.PhoneNumber.objects.filter(id=nid).delete()
    return redirect("/phonenumber")


# 编辑靓号
def number_edit(request, nid):
    row_obj = models.PhoneNumber.objects.filter(id=nid).first()
    if request.method == "GET":
        form = edit(instance=row_obj)
        return render(request, "number_edit.html", {"form": form})
    else:
        form = edit(data=request.POST, instance=row_obj)
        if form.is_valid():
            form.save()
            return redirect("/phonenumber/")
        return render(request, 'number_add.html', {"form": form})


# from django.core.files.uploadedfile
# 文件上传
class upform(Form):
    username = forms.CharField(label="用户名")
    password = forms.CharField(label="密码")
    img = forms.FileField(label="头像")
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    # for name, field in self.fields.items():
    #     field.widget.attrs = {"class": "form-control", "placeholder": field.label}


def load_file(request):
    title = "文件上传"
    if request.method == "GET":
        form = upform()
        return render(request, "file.html", {"form": form, "title": title})
    form = upform(data=request.POST, files=request.FILES)
    if form.is_valid():
        image_obj = form.cleaned_data.get("img")
        db_img_path = os.path.join("static/", "img/", image_obj.name)
        print(db_img_path)
        img_path = os.path.join("app1", "static", "img", image_obj.name)
        f = open(img_path, mode="wb")
        for chunk in image_obj.chunks():
            f.write(chunk)
        f.close()
        # 写入数据库
        models.Admin1.objects.create(
            username=form.cleaned_data["username"],
            password=form.cleaned_data['password'],
            img=db_img_path,
        )
        return redirect("/" + db_img_path)
    return render(request, "file.html", {"form": form, "title": title})


from django import forms
from app02.utils.bootstrap import BootStrapModelForm


class upmodelform(BootStrapModelForm):
    class Meta:
        model = models.city
        fields = "__all__"


def moelformfile(request):
    title = "ModelForm上传文件"
    if request.method == "GET":
        form = upmodelform()
        return render(request, "file.html", {"form": form, "title": title})
    form = upmodelform(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect("/city/")
    return render(request, "file.html", {"form": form, "title": title})


def citys(request):
    if request.method == "GET":
        quersey = models.city.objects.all()
        return render(request, "city.html", {"quersey": quersey})


# 添加用户基于ModelForm
# from django import forms
#
# class UserModelForm(forms.ModelForm):
#     class Meta:
#         model = models.UserInfo
#         fiedls = ["name","password","age","account"]
#
#
# def user_add(request):
#     form = UserModelForm()
#     return render(request,"user_add.html",{"form":form})
'''
#添加用户
def add(request):
    if request.method == "GET":
        return render(request,"add.html")
    else:
        user_name =request.POST.get("name")
        user_password = request.POST.get("password")
        user_age = request.POST.get("age")
        UserInfo.objects.create(name=user_name,password=user_password,age=user_age)
        return redirect(信息展示页的路由)

文件
    # if request.method == "GET":
    #     return render(request, "file.html")
    # file_obj = request.FILES.get("avator")
    # f = open(file_obj.name,mode='wb')
    # for chunk in file_obj.chunks():
    #     f.write(chunk)
    # print(f)
    # f.close()
    # return HttpResponse('1233')


#删除用户
def delete(request):
    nid=request.GET.get("nid")
    UserInfo.objects.filter(id=nid).delte()
    return redirect('信息展示页路由')
'''

django_class/djangoProject2/app02/templates/city.html
{% extends 'layout.html' %}
{% block content %}
     <div class="container">
        <div>
            <a class="btn btn-primary" href="/modelfile/" >
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建城市信息</a>
        </div>
        <div>
            <div class="bs-example" data-example-id="panel-without-body-with-table">
            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading">列表</div>

              <!-- Table -->
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>城市名称</th>
                    <th>城市人口</th>
                    <th>LOGO</th>
                  </tr>
                </thead>
                <tbody>
                {% for obj in quersey %}
                    <tr>
                    <th scope="row">{{ obj.id }}</th>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.count }}</td>
                    <td>
                        <img src="/media/{{ obj.img }}" alt="城市logo" style="width: 200px;height: 60px">
                    </td>
                  </tr>
                {% endfor %}


                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

django_class/djangoProject2/app02/templates/depart.html
{% extends 'layout.html' %}
{% block content %}
     <div class="container">
        <div>
            <a class="btn btn-primary" href="/depart/add" >
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建部门</a>
        </div>
        <div>
            <div class="bs-example" data-example-id="panel-without-body-with-table">
            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading">列表</div>

              <!-- Table -->
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>名称</th>
                    <th>操作</th>
                  </tr>
                </thead>
                <tbody>
                {% for obj in quersey %}
                    <tr>
                    <th scope="row">{{ obj.id }}</th>
                    <td>{{ obj.title }}</td>
                    <td>
                        <a href="/depart/{{ obj.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                        <a href="/depart/delete/?nid={{ obj.id }}" class="btn btn-danger btn-xs">删除</a>
                    </td>
                  </tr>
                {% endfor %}


                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

django_class/djangoProject2/app02/templates/depart_add.html
{% extends 'layout.html' %}
{% block content %}
        <div class="container">
        <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">部门添加</h3>
              </div>
              <div class="panel-body">
                <form class="form-horizontal"  method="post">
                    {% csrf_token %}
                  <div class="form-group">
                    <label  class="col-sm-2 control-label">标题</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control"  placeholder="标题" name="title"/>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-primary">提交</button>
                    </div>
                  </div>
                </form>
              </div>
        </div>
    </div>
{% endblock %}

django_class/djangoProject2/app02/templates/depart_edit.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">部门编辑</h3>
              </div>
              <div class="panel-body">
                <form class="form-horizontal"  method="post">
                    {% csrf_token %}
                  <div class="form-group">
                    <label  class="col-sm-2 control-label">标题</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" value="{{ value }}" placeholder="标题" name="title"/>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-primary">提交</button>
                    </div>
                  </div>
                </form>
              </div>
        </div>
    </div>
{% endblock %}

django_class/djangoProject2/app02/templates/file.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel-default panel">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    {% for item in form %}
                        <div class="form-group">
                            <label>{{ item.label }}</label>
                            {{ item }}
                            <span style="color: red">{{ item.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn-primary btn">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

django_class/djangoProject2/app02/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">用户管理系统</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/user/">用户管理</a></li>
        <li><a href="/depart/">部门管理</a></li>
        <li><a href="/phonenumber/">靓号管理</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">登录</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> hei<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">用户名称</a></li>
            <li><a href="#">个人资料</a></li>
            <li><a href="#">注销</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">退出登录</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div>
          {% block content %}{% endblock %}
</div>
</body>
</html>

django_class/djangoProject2/app02/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="login">
        <form action="/login/" method="post" class="loginform">
            {% csrf_token %}
            <table>
                <tr>
                    <td>用户:</td>
                    <td><input type="text" placeholder="用户" name="username"></td>
                </tr>
                <tr>
                    <td>密码:</td>
                    <td><input type="password" placeholder="密码" name="password"></td>
                </tr>

            </table>
            <input type="submit" value="登录" class="sub">
        </form>
        {{ mseeage }}
    </div>
</body>
<style>

    .login{
        margin:0 auto;
        width:400px;
    }
    .loginform{
        width:400px;
        height:300px;
        border:1px solid black;
        border-radius: 20%;
        position: relative;
        top:160px;
        background-color: rgb(169,143,155);
        {#opacity: 0.5;#}
    }
    table{
        position: absolute;
        top:0;
        left:0;
        right:0;
        bottom: 0;
        margin: auto;
    }
    table td input{
        width:200px;
        height:40px;
        border-radius: 6%;
        opacity: 0.5;
    }
    body{
        background-image: url("https://img.keaitupian.cn/newupload/08/1629449018344288.jpg");
        background-size: cover;
        background-repeat: no-repeat;
    }
    .sub{
        position: absolute;
        top:220px;
        left:40%;
        width:100px;
        opacity: 0.5;
        height:40px;

    }
</style>
</html>

django_class/djangoProject2/app02/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

django_class/djangoProject2/app02/templates/number.html
{% extends 'layout.html' %}
{% block content %}
       <div class="container">
        <div>
            <a class="btn btn-primary" href="/phonenumber/add/" >
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                添加靓号</a>
             <div class="search" style="float: right;width:300px">
                 <form method="get">

                   <div class="input-group">
                      <input type="text" class="form-control" name="q" placeholder="号码查询" value={{ dates }}>
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                   </div>
                 </form>
            </div>
        </div>
        <div>
            <div class="bs-example" data-example-id="panel-without-body-with-table">
            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading">靓号列表</div>

              <!-- Table -->
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>手机号</th>
                    <th>价格</th>
                    <th>级别</th>
                    <th>状态</th>
                    <th>操作</th>
                  </tr>
                </thead>
                <tbody>
                {% for obj in number %}
                    <tr>
                    <th scope="row">{{ obj.id }}</th>
                    <td>{{ obj.number }}</td>
                     <td>{{ obj.price }}</td>
                     <td>{{ obj.get_level_display }}</td>
                     <td>{{ obj.get_status_display}}</td>
                    <td>
                        <a href="/phonenumber/{{ obj.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                        <a href="/phonenumber/delete/?nid={{ obj.id }}" class="btn btn-danger btn-xs">删除</a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

django_class/djangoProject2/app02/templates/number_add.html
{% extends 'layout.html' %}
{% block content %}
            <div class="container">
        <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">添加靓号</h3>
              </div>
              <div class="panel-body">
                <form class="form-horizontal"  method="post" novalidate>
                    {% csrf_token %}
                    {% for item in form %}
                        <div class="form-group">
                            <label  class="col-sm-2 control-label">{{ item.label }}</label>
                            <div class="col-sm-10">
                             {{ item }}
                              <span style="color: red"> {{ item.errors.0 }} </span>
                            </div>
                        </div>
                    {% endfor %}
                 <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-primary">提交</button>
                    </div>
                  </div>
                </form>
              </div>
        </div>
    </div>
{% endblock %}

django_class/djangoProject2/app02/templates/number_edit.html
{% extends 'layout.html' %}
{% block content %}
         <div class="container">
        <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">修改信息</h3>
              </div>
              <div class="panel-body">
                <form class="form-horizontal"  method="post" novalidate>
                    {% csrf_token %}
                    {% for item in form %}
                        <div class="form-group">
                            <label  class="col-sm-2 control-label">{{ item.label }}</label>
                            <div class="col-sm-10">
                             {{ item }}
                              <span style="color: red"> {{ item.errors.0 }} </span>
                            </div>
                        </div>
                    {% endfor %}
                 <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-primary">提交</button>
                    </div>
                  </div>
                </form>
              </div>
        </div>
    </div>
{% endblock %}

django_class/djangoProject2/app02/templates/user.html
{% extends 'layout.html' %}
{% block content %}
     <div class="container">
        <div>
            <a class="btn btn-primary" href="/user/add" >
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                添加用户</a>
        </div>
        <div>
            <div class="bs-example" data-example-id="panel-without-body-with-table">
            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading">用户列表</div>

              <!-- Table -->
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>账户余额</th>
                    <th>入职时间</th>
                    <th>性别</th>
                    <th>部门</th>
                    <th>操作</th>
                  </tr>
                </thead>
                <tbody>
                {% for obj in users %}
                    <tr>
                    <th scope="row">{{ obj.id }}</th>
                    <td>{{ obj.name }}</td>
                     <td>{{ obj.password }}</td>
                     <td>{{ obj.age }}</td>
                     <td>{{ obj.account }}</td>
                     <td>{{ obj.enroll|date:"Y-m-d"}}</td>
                     <td>{{ obj.get_gender_display }}</td>
                      <td>{{ obj.depart.title }}</td>
                    <td>
                        <a href="/user/{{ obj.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                        <a href="/user/delete/?nid={{ obj.id }}" class="btn btn-danger btn-xs">删除</a>
                    </td>
                  </tr>
                {% endfor %}


                </tbody>
              </table>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

django_class/djangoProject2/app02/templates/user_add.html
{% extends 'layout.html' %}
{% block content %}
        <div class="container">
        <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">添加用户</h3>
              </div>
              <div class="panel-body">
                <form class="form-horizontal"  method="post">
                    {% csrf_token %}
                    {% for item in form %}
                        <div class="form-group">
                            <label  class="col-sm-2 control-label">{{ item.label }}</label>
                            <div class="col-sm-10">
                             {{ item }}
                              <span style="color: red"> {{ item.errors.0 }} </span>
                            </div>
                        </div>
                    {% endfor %}
                 <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-primary">提交</button>
                    </div>
                  </div>
                </form>
              </div>
        </div>
    </div>
{% endblock %}

django_class/djangoProject2/app02/templates/user_edit.html
{% extends "layout.html" %}
{% block content %}
      <div class="container">
        <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">添加用户</h3>
              </div>
              <div class="panel-body">
                <form class="form-horizontal"  method="post">
                    {% csrf_token %}
                    {% for item in form %}
                        <div class="form-group">
                            <label  class="col-sm-2 control-label">{{ item.label }}</label>
                            <div class="col-sm-10">
                             {{ item }}
                              <span style="color: red"> {{ item.errors.0 }} </span>
                            </div>
                        </div>
                    {% endfor %}
                 <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-primary">提交</button>
                    </div>
                  </div>
                </form>
              </div>
        </div>
    </div>
{% endblock %}